Repository AY2223S2-CS2103T-W09-4/tp, pull requests merged in 2023-03, with the labels that each got.

#104 Find Command update
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/employee/EmployeeId.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Story, priority.High

#115 Add Assert test
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/employee/EmployeeId.java
Labels: priority.Medium

#124 Remove fields from EmployeeCard
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.High

#127 Fix UI Picture Bug
  src/main/resources/view/PersonListPanel.fxml
Labels: priority.High

#136 Add assertions
  src/main/java/seedu/address/commons/util/StringUtil.java
Labels: priority.Medium

#133 Update test files to pass test cases
  src/main/java/seedu/address/logic/commands/BatchAddCommand.java
  src/main/java/seedu/address/model/employee/Address.java
  src/main/java/seedu/address/model/employee/Email.java
  src/main/java/seedu/address/model/employee/Phone.java
  src/test/data/BatchAddTest/BatchAddSuccess.csv
  src/test/data/BatchAddTest/duplicates.csv
  src/test/data/BatchAddTest/emptyFile.csv
  src/test/data/JsonSerializableExecutiveProDbTest/duplicateEmployeeExecutiveProDb.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/BatchAddCommandTest.java
  src/test/java/seedu/address/model/ExecutiveProDbTest.java
  src/test/java/seedu/address/model/employee/EmployeeTest.java
  src/test/java/seedu/address/model/employee/UniqueEmployeeListTest.java
  src/test/java/seedu/address/testutil/EmployeeBuilder.java
  src/test/java/seedu/address/testutil/TypicalEmployees.java
Labels: type.Bug, priority.High

#142 Update Find Command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/employee/NameContainsAllKeywordsPredicate.java
  src/main/java/seedu/address/model/employee/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/CommandFormat.java
Labels: priority.High

#146 Change PPP's images into images folder
  docs/AboutUs.md
  docs/images/abenx162.png
  docs/images/gyulong1.png
  docs/images/junhao247.png
  docs/images/panavdua.png
  docs/images/yanlings.png
Labels: type.Task, priority.High

#147 Change font size
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListPanel.fxml
Labels: priority.Medium

#153 Update UG for Theme and SetPicture commands
  docs/UserGuide.md
  docs/images/UserGuide/SetPictureCommand1.png
  docs/images/UserGuide/SetPictureCommand2.png
  docs/images/UserGuide/SetPictureCommand3.png
  docs/images/UserGuide/ThemeCommandDark.png
  docs/images/UserGuide/ThemeCommandLight.png
Labels: priority.Medium

#177 Update user guide with updated Ui image and update version number
  docs/images/Ui.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/UserGuide/BatchAddSuccess.png
  docs/images/UserGuide/Ui.png
  docs/images/UserGuide/exportedFile.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/employee/FilterByLeaveCountPredicate.java
  src/main/java/seedu/address/model/employee/FilterByPayrollPredicate.java
Labels: type.Enhancement, priority.High
